[variables]
    NIXPACKS_PHP_VERSION = '8.3'
    NIXPACKS_NODE_VERSION = '22'

[phases.setup]
    nixPkgs = ['php83', 'nodejs_22', 'php83Packages.composer']
[phases.build]
# Runs composer install, npm install, and the build script
cmds = [
  "composer install",
  "npm ci",
  "npm run build"
]

