[variables]
    NIXPACKS_PHP_VERSION = '8.4'
    NIXPACKS_NODE_VERSION = '22'

[phases.setup]
    nixPkgs = ['php84', 'nodejs_22', 'php84Packages.composer','nginx', 'libmysqlclient']

[phases.build]
    # Usamos cmds para ejecutar varios comandos en orden
    cmds = [
        'composer install --no-interaction --optimize-autoloader',
        'php artisan optimize:clear',
        'php artisan optimize'
    ]

[processes]
    # Añadimos el migrate aquí, antes de lanzar los servicios
    web = 'php artisan migrate --force'